import { UserPartial } from 'models/User.ts';
// {
//     {
//         about: '',
//             avatarPath: '',
//         gallery: [],
//         id: 'uid-1234567890123',
//         lastSeen: new Date().getTime() - Math.floor(Math.random() * 1000000),
//         name: 'Sergey Chichikov',
//         num: 'user-1234567890123',
//         status: 'is-online',
//         ver: '1',
//     },
//     {
//         about: '',
//             avatarPath: '',
//         gallery: [],
//         id: 'uid-1234567890124',
//         lastSeen: new Date().getTime() - Math.floor(Math.random() * 1000000),
//         name: 'Valeriy Chichikov',
//         num: 'user-1234567890124',
//         status: 'is-busy',
//         ver: '1',
//     },
//     {
//         about: '',
//             avatarPath: '',
//         gallery: [],
//         id: 'uid-1234567890125',
//         lastSeen: new Date().getTime() - Math.floor(Math.random() * 1000000),
//         name: 'Igor Chizhikov',
//         num: 'user-1234567890125',
//         status: 'is-away',
//         ver: '1',
//     },
//     {
//         about: '',
//             avatarPath: exampleAvatar,
//         gallery: [],
//         id: 'uid-1234567890126',
//         lastSeen: new Date().getTime() - Math.floor(Math.random() * 1000000),
//         name: 'Ilya Pizhikov',
//         num: 'user-1234567890126',
//         status: 'is-live',
//         ver: '1',
//     },
//     {
//         about: '',
//             avatarPath: exampleAvatar,
//         gallery: [],
//         id: 'uid-1234567890127',
//         lastSeen: new Date().getTime() - Math.floor(Math.random() * 1000000),
//         name: 'Irina Richikova',
//         num: 'user-1234567890127',
//         status: 'is-online',
//         ver: '1',
//     },
//     {
//         about: '',
//             avatarPath: exampleAvatar,
//         gallery: [],
//         id: 'uid-1234567890128',
//         lastSeen: new Date().getTime() - Math.floor(Math.random() * 1000000),
//         name: 'Dmitriy Kuchik',
//         num: 'user-1234567890128',
//         status: 'is-offline',
//         ver: '1',
//     },
//     {
//         about: '',
//             avatarPath: exampleAvatar,
//         gallery: [],
//         id: 'uid-1234567890129',
//         lastSeen: new Date().getTime() - Math.floor(Math.random() * 1000000),
//         name: 'Anna Beglaya',
//         num: 'aser-1234567890129',
//         status: 'is-busy',
//         ver: '1',
//     },
//     {
//         about: '',
//             avatarPath: exampleAvatar,
//         gallery: [],
//         id: 'uid-1234567890130',
//         lastSeen: new Date().getTime() - Math.floor(Math.random() * 1000000),
//         name: 'Rodion Dyatlov',
//         num: 'bser-1234567890130',
//         status: 'is-away',
//         ver: '1',
//     },
//     {
//         about: '',
//             avatarPath: exampleAvatar,
//         gallery: [],
//         id: 'uid-1234567890131',
//         lastSeen: new Date().getTime() - Math.floor(Math.random() * 1000000),
//         name: 'Nikolay Dudkin',
//         num: 'user-1234567890131',
//         status: 'is-away',
//         ver: '1',
//     },
//     {
//         about: '',
//             avatarPath: exampleAvatar,
//         gallery: [],
//         id: 'uid-1234567890132',
//         lastSeen: new Date().getTime() - Math.floor(Math.random() * 1000000),
//         name: 'Valeriya Chichikova',
//         num: 'user-1234567890132',
//         status: 'is-away',
//         ver: '1',
//     },
//     {
//         about: '',
//             avatarPath: exampleAvatar,
//         gallery: [],
//         id: 'uid-1234567890133',
//         lastSeen: new Date().getTime() - Math.floor(Math.random() * 1000000),
//         name: 'Mariya Pochkova',
//         num: 'user-1234567890133',
//         status: 'is-away',
//         ver: '1',
//     },
//     {
//         about: '',
//             avatarPath: exampleAvatar,
//         gallery: [],
//         id: 'uid-1234567890134',
//         lastSeen: new Date().getTime() - Math.floor(Math.random() * 1000000),
//         name: 'Valeriy Chichikov',
//         num: 'user-1234567890134',
//         status: 'is-away',
//         ver: '1',
//     },
//     {
//         about: '',
//             avatarPath: exampleAvatar,
//         gallery: [],
//         id: 'uid-1234567890135',
//         lastSeen: new Date().getTime() - Math.floor(Math.random() * 1000000),
//         name: 'Valeriy Chichikovkin',
//         num: 'user-1234567890134',
//         status: 'is-away',
//         ver: '1',
//     },
//     {
//         about: '',
//             avatarPath: exampleAvatar,
//         gallery: [],
//         id: 'uid-1234567890136',
//         lastSeen: new Date().getTime() - Math.floor(Math.random() * 1000000),
//         name: 'Valeriy Chichikovkich',
//         num: 'user-1234567890134',
//         status: 'is-away',
//         ver: '1',
//     },
//     {
//         about: '',
//             avatarPath: '',
//         gallery: [],
//         id: 'uid-1',
//         lastSeen: new Date().getTime() - Math.floor(Math.random() * 1000000),
//         name: 'Valeriy Chichikov',
//         num: 'user-1',
//         status: 'is-online',
//         ver: '1',
//     },
// }
export default [] as UserPartial[];
