kind: Secret
apiVersion: v1
metadata:
  name: {{ printf "%s.cred" (include "medea.fullname" .) | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    helm.sh/chart: {{ include "medea.chart" . | quote }}
    app.kubernetes.io/name: {{ include "medea.name" . | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
  {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- $medeaConf := .Values.conf }}
  {{- $coturnConf := .Values.coturn.conf }}
  {{- $coturnDbConf := index .Values "coturn-db" "conf" }}
  MEDEA_TURN__PASS: {{ $medeaConf.turn.pass | b64enc | quote }}
  MEDEA_TURN__DB__REDIS__PASS: {{ $coturnDbConf.requirepass | b64enc | quote }}
  MEDEA_TURN__CLI__PASS: {{ index $coturnConf "cli-password" | b64enc | quote }}
