/**
 * Conversation menu states.
 */
export enum StateTypes {
    NOT_ACTIVE,
    ACTIONS,
    CONTACT_BLOCKED,
    CONTACT_SHARE,
    CONFIRM_BLOCK_CONTACT,
    CONVERSATION_FAVOURITE_ADDED,
    CONVERSATION_FAVOURITE_REMOVED,
    CONVERSATION_REMOVED,
    CONFIRM_RENAME_CONVERSATION,
    CONFIRM_REMOVE_CONVERSATION,
    CONVERSATION_SUPPORT,
    CONVERSATION_SUPPORT_CONFIRM,
    CONVERSATION_SUPPORT_SENT,
    CONVERSATION_SUPPORTED,
    CONVERSATION_SUPPORT_FAIL,
}
