image:
  repository: hub.instrumentisto.com/social/frontend
  tag: latest
  pullPolicy: IfNotPresent
  credentials:
    registry: hub.instrumentisto.com
    username: proj-social-frontend
    password: m7DjZq2Ccj4pGZqfSVUSSeSsh

# Additional labels to apply to all Kubernetes resources created by this chart.
labels: {}
  # app.kubernetes.io/part-of: frontend

deployment:
  replicas: 1
  revisionHistoryLimit: 0

  # Optional revision number that may used for fine-grained Deployment rollouts.
  revision: ""

  annotations: {}
    # kubernetes.io/change-cause=kubectl set ...

  affinity: {}
    # nodeAffinity:
    #   requiredDuringSchedulingIgnoredDuringExecution:
    #     nodeSelectorTerms:
    #       - matchExpressions:
    #         - key: node-label-key
    #           operator: In
    #           values: ["node-label-value"]

  tolerations: []
    # - key: "node.alpha.kubernetes.io/unreachable"
    #   operator: "Exists"
    #   effect: "NoExecute"

  resources: {}
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  # Container sources may be mounted to the specified host path.
  # This allows to develop the project without rebuilding container each time.
  src:
    hostPath: ""

service:
  type: ClusterIP

ingress:
  enabled: yes

  # Hosts must be specified without "www." part.
  hosts:
    - frontend.test

  tls:
    enabled: no
    auto: no
    # Not required when "auto" is enabled.
    secretName:
      frontend.test: frontend.test.tls

  httpAuth:
    enabled: no
    # Content of htpasswd file.
    htpasswd: ""

  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: "30m"


nginx:
  image:
    repository: nginx
    tag: stable-alpine
    pullPolicy: IfNotPresent

  resources: {}
    # limits:
    #   cpu: 200m
    #   memory: 1Gi
    # requests:
    #   cpu: 100m
    #   memory: 100Mi


sftp:
  enabled: no

  image:
    repository: atmoz/sftp
    tag: latest
    pullPolicy: IfNotPresent

  port: ""
  user: user
  pass: changeme

  resources: {}
    # limits:
    #   cpu: 50m
    #   memory: 5Mi
    # requests:
    #   cpu: 1m
    #   memory: 1Mi


backend:
  deploy: no
  existing:
    service:
      name: socback
      port:
        name: http

  # See `@social-backend/backend` Helm chart options:
  # https://git.instrumentisto.com/social/backend/blob/master/helm/backend/values.yaml
  # deploy: yes
  image:
    repository: hub.instrumentisto.com/social/backend
    tag: latest
    pullPolicy: IfNotPresent
    credentials:
      registry: hub.instrumentisto.com
      username: proj-social-frontend
      password: m7DjZq2Ccj4pGZqfSVUSSeSsh
  deployment:
    replicas: 1
  ingress:
    enabled: no
  monitoring:
    enabled: no

  cockroachdb:
    deploy: no

    # See `@stable/cockroachdb` Helm chart options:
    # https://github.com/helm/charts/blob/master/stable/cockroachdb/values.yaml
    # deploy: yes
    image:
      repository: hub.instrumentisto.com/social/backend/db/cockroachdb
      tag: latest
      pullPolicy: IfNotPresent
      credentials:
        registry: hub.instrumentisto.com
        username: proj-social-frontend
        password: m7DjZq2Ccj4pGZqfSVUSSeSsh

  filestorage:
    deploy: no

    # See `@stable/minio` Helm chart options:
    # https://github.com/helm/charts/blob/master/stable/minio/values.yaml
    # deploy: yes
    accessKey: changeme
    secretKey: changeme

  medea:
    controlUrl: http://localhost/medea-control-mock/control-api


filestorage:
  # NOTE: These options are auto-wired if `backend.filestorage` service above
  #       is enabled via `deploy: yes`. Specifying them in this configuration
  #       will have no effect.
  existing:
    service:
      name: filestorage
      port:
        name: http


# See Medea Helm sub-chart options in the `charts/medea/values.yaml` file.
medea:
  image:
    tag: edge
    pullPolicy: Always

  ingress:
    enabled: no

  control-mock:
    image:
      tag: edge
      pullPolicy: Always

  coturn:
    image:
      tag: "4.5"
  coturn-db:
    image:
      tag: alpine
