kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ include "frontend.fullname" . | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    helm.sh/chart: {{ include "frontend.chart" . | quote }}
    app.kubernetes.io/name: {{ include "frontend.name" . | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/component: app
  {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.deployment.replicas | int }}
  revisionHistoryLimit: {{ .Values.deployment.revisionHistoryLimit | int }}
{{- if gt (.Values.deployment.replicas | int) 1 }}
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0
{{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "frontend.name" . | quote }}
      app.kubernetes.io/instance: {{ .Release.Name | quote }}
      app.kubernetes.io/component: app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "frontend.name" . | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        app.kubernetes.io/component: app
      {{- with .Values.labels }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      annotations:
        checksum/conf: {{ pick (include (print $.Template.BasePath "/configmap.yaml") . | fromYaml) "data" | toYaml | sha256sum | quote }}
      {{- if .Values.sftp.enabled }}
        checksum/sftp: {{ pick (include (print $.Template.BasePath "/secret.sftp.yaml") . | fromYaml) "data" | toYaml | sha256sum | quote }}
      {{- end }}
      {{- with .Values.deployment.revision }}
        revision: {{ . | quote }}
      {{- end }}
      {{- with .Values.deployment.annotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
    {{- with .Values.deployment.affinity }}
      affinity: {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.deployment.tolerations }}
      tolerations: {{- toYaml . | nindent 8 }}
    {{- end }}
      securityContext:
        fsGroup: 1000  # 'node' user
      imagePullSecrets:
        - name: {{ printf "%s.registry" (include "frontend.fullname" .) | quote }}
      containers:
        - name: app
          image: {{ printf "%s:%s" .Values.image.repository .Values.image.tag | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        {{- if empty .Values.deployment.src.hostPath }}
          env:
            - name: SHARE_APP
              value: '1'
        {{- end }}
          volumeMounts:
            - name: src
            {{- if .Values.deployment.src.hostPath }}
              subPath: out/
              mountPath: /app/
            - name: src
              subPath: node_modules/
              mountPath: /app/node_modules/
            {{- else }}
              mountPath: /shared/
            {{- end }}
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
        {{- with .Values.deployment.resources }}
          resources: {{- toYaml . | nindent 12 }}
        {{- end }}
        - name: nginx
          image: {{ printf "%s:%s" .Values.nginx.image.repository .Values.nginx.image.tag | quote }}
          imagePullPolicy: {{ .Values.nginx.image.pullPolicy | quote }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: src
            {{- if .Values.deployment.src.hostPath }}
              subPath: out/public/
            {{- else }}
              subPath: public/
            {{- end }}
              mountPath: /var/www/public/
              readOnly: true
            - name: conf
              subPath: nginx.vh.conf
              mountPath: /etc/nginx/conf.d/default.conf
              readOnly: true
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 5
        {{- with .Values.nginx.resources }}
          resources: {{- toYaml . | nindent 12 }}
        {{- end }}
        - name: mock-api
          image: {{ printf "%s:%s" .Values.image.repository .Values.image.tag | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          args: ["node", "./api-mock-server.js"]
          env:
            - name: MEDEA_HOST
              value: {{ .Values.backend.medea.controlUrl | quote }}
          volumeMounts:
            - name: src
            {{- if .Values.deployment.src.hostPath }}
              subPath: out/public/uploads/
            {{- else }}
              subPath: public/uploads/
            {{- end }}
              mountPath: /app/out/public/uploads/
          readinessProbe:
            tcpSocket:
              port: 8086
            initialDelaySeconds: 5
        {{- with .Values.deployment.resources }}
          resources: {{- toYaml . | nindent 12 }}
        {{- end }}
      {{- if .Values.sftp.enabled }}
        - name: sftp
          image: {{ printf "%s:%s" .Values.sftp.image.repository .Values.sftp.image.tag | quote }}
          imagePullPolicy: {{ .Values.sftp.image.pullPolicy | quote }}
          args: ["$(SFTP_USER):$(SFTP_PASSWORD):1000:1000"]
          ports:
            - name: sftp
              containerPort: 22
              protocol: TCP
          envFrom:
            - secretRef:
                name: {{ printf "%s.sftp" (include "frontend.fullname" .) | quote }}
          volumeMounts:
            - name: src
            {{- if .Values.deployment.src.hostPath }}
              subPath: out/
            {{- end }}
              mountPath: {{ printf "/home/%s/app/" .Values.sftp.user | quote }}
        {{- with .Values.sftp.resources }}
          resources: {{- toYaml . | nindent 12 }}
        {{- end }}
      {{- end }}
      volumes:
        - name: conf
          configMap:
            name: {{ printf "%s.conf" (include "frontend.fullname" .) | quote }}
        - name: src
        {{- if .Values.deployment.src.hostPath }}
          hostPath:
            path: {{ .Values.deployment.src.hostPath | quote }}
        {{- else }}
          emptyDir: {}
        {{- end }}
